import {useState} from 'react';
import {session,authHeaders} from './auth';
const base=import.meta.env.VITE_API_URL||'';
export default function Account(){
 const [user,setUser]=useState(session()),[name,setName]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function login(){setBusy(true);setError('');try{const r=await fetch(`${base}/api/v1/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:name,password})});const d=await r.json();if(!r.ok)throw Error(d.detail);sessionStorage.setItem('vayu-session',JSON.stringify(d));setUser(d);setPassword('');}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function logout(){try{await fetch(`${base}/api/v1/auth/logout`,{method:'POST',headers:authHeaders()});}finally{sessionStorage.removeItem('vayu-session');setUser(null);}}
 return <article className="panel workflow"><span className="eyebrow">1 · SIGN IN TO RECORD ACTIONS</span><h2>Operator and reviewer accounts</h2><p>Browsing and scenario planning stay available without an account. Evidence updates use the signed-in identity. Only the assigned operator can complete an action; a separate reviewer must verify it.</p>{user?<><p>Signed in as <strong>{user.username}</strong> · {user.role}. Sessions expire after eight hours.</p><button className="button" onClick={()=>void logout()}>Sign out</button></>:<><p>Create accounts in the server terminal using <code>create-account.cmd</code>. Use separate operator and reviewer accounts.</p><div className="field-grid"><label>Username<input autoComplete="username" value={name} onChange={e=>setName(e.target.value)}/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label></div><button className="button primary" disabled={busy||!name||!password} onClick={()=>void login()}>Sign in</button></>}{error&&<p role="alert">{error}</p>}</article>;
}
