import {useEffect,useState} from 'react';
const base=import.meta.env.VITE_API_URL||'';
type Run={id:number;city:string;at:string;ok:number;detail:string;archive:string|null};
export default function Collections(){
 const [runs,setRuns]=useState<Run[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function load(){try{const r=await fetch(`${base}/api/v1/collections`);if(!r.ok)throw Error('Collection archive unavailable');setRuns((await r.json()).runs);const n=await fetch(`${base}/api/v1/notifications`);if(n.ok){const d=await n.json();setNotice(`Delivery: ${d.enabled?'enabled':'dry-run / local only'}. SMTP ${d.smtp_configured?'configured':'not configured'}; SMS provider ${d.sms_configured?'configured':'not configured'}. ${d.deliveries.length} recent queue entries.`);}setError('');}catch(e){setError(String(e));}}
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),30000);return()=>clearInterval(timer);},[]);
 const latest=runs.filter((r,i)=>runs.findIndex(x=>x.city===r.city)===i).sort((a,b)=>a.city.localeCompare(b.city));
 return <article className="panel workflow"><span className="eyebrow">LIVE COLLECTION ARCHIVE</span><h2>Where your data is saved</h2><p>Full collection snapshots: <code>data/processed/collections/&lt;city&gt;/&lt;timestamp&gt;.json</code>. Status, alert and audit records: <code>data/processed/operations.sqlite3</code>. Measured station history is saved separately from regional forecasts.</p><p>Run <code>run-monitor.cmd</code> for every configured location. A successful collection may include regional model estimates; it does not mean both pollutants were measured locally. Failed attempts remain visible. Refreshes automatically every 30 seconds.</p><p>{notice}</p><button className="button" onClick={()=>void load()}>Refresh collections</button><details><summary>{latest.length} locations attempted · {latest.filter(r=>r.ok).length} latest successful · expand saved files</summary><div className="table-scroll"><table><thead><tr><th>Location</th><th>Collected</th><th>Result / source quality</th><th>Saved file</th></tr></thead><tbody>{latest.map(r=><tr key={r.id}><td>{r.city}</td><td>{new Date(r.at).toLocaleString()}</td><td>{r.ok?'Saved':'Failed'} · {r.detail}</td><td>{r.archive?<a href={`${base}/api/v1/collections/${r.id}/download`} download>Download JSON</a>:'No snapshot'}</td></tr>)}</tbody></table></div></details>{error&&<p role="alert">{error}</p>}</article>;
}
