import {useEffect,useState} from 'react';
type Option={name:string;cost:number;pm25_reduction_pct:number;pm10_reduction_pct:number;start_hour:number;end_hour:number};
type Result={selected:Option[];cost:number;baseline_peak_hours:number;scenario_peak_hours:number;scenario_reduction_pct:number|null;note:string;forecast_start:string;forecast_end:string};
const base=import.meta.env.VITE_API_URL||'';
export default function Planner({city,mode='live'}:{city:string;mode?:'live'|'demo'}) {
 const [options,setOptions]=useState<Option[]>([]),[budget,setBudget]=useState(0),[result,setResult]=useState<Result|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [entry,setEntry]=useState<Option>({name:'',cost:0,pm25_reduction_pct:0,pm10_reduction_pct:0,start_hour:1,end_hour:24});
 const [example,setExample]=useState(false);
 function applySample(d:{options:Option[];budget:number}){if(!Array.isArray(d.options)||d.options.length<1||d.options.length>12||!Number.isFinite(d.budget)||d.budget<0||d.options.some(o=>!o.name||![o.cost,o.pm25_reduction_pct,o.pm10_reduction_pct,o.start_hour,o.end_hour].every(Number.isFinite)||o.cost<0||o.pm25_reduction_pct<0||o.pm25_reduction_pct>80||o.pm10_reduction_pct<0||o.pm10_reduction_pct>80||o.start_hour<1||o.end_hour>24||o.start_hour>o.end_hour))throw Error('Invalid planner file: use the downloadable JSON format.');setOptions(d.options);setBudget(d.budget);setExample(true);setResult(null);}
 async function sample(){try{const r=await fetch(`${base}/api/v1/samples/planner-example.json`);if(!r.ok)throw Error('Sample file unavailable');applySample(await r.json());}catch(e){setError(String(e));}}
 useEffect(()=>{if(mode==='demo')void sample();},[city,mode]);
 async function run(){setBusy(true);setError('');setResult(null);try{const r=await fetch(`${base}/api/v1/plan`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({city,mode,budget,options})});const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'Check action costs, percentages and integer hours.');setResult(d);}catch(e){setError(String(e));}finally{setBusy(false);}}
 const valid=entry.name.trim()&&entry.cost>=0&&entry.start_hour>=1&&entry.end_hour<=24&&entry.start_hour<=entry.end_hour&&entry.pm25_reduction_pct>=0&&entry.pm25_reduction_pct<=80&&entry.pm10_reduction_pct>=0&&entry.pm10_reduction_pct<=80;
 return <article className="panel workflow"><span className="eyebrow">2 · COMPARE FEASIBLE ACTIONS</span><h2>{mode==='demo'?'Presentation scenario · prefilled example':'Plan an operator-approved intervention'}</h2>
 <p>Goal: choose a combination that reduces forecast hours at screening index 151 or higher within your budget. Ties favour lower total index, then lower cost. This is an assumption-based comparison, not proof of a facility's effect.</p>
 <p><strong>What to enter:</strong> the cost for the whole action and the assumed reduction in ambient concentration during its active hours. These percentages are not stack-emission removal efficiency. Hour 1 is the first forecast timestamp; hour 24 is the final one. Overlapping effects combine multiplicatively.</p>
 <div className="workflow-tools"><button className="button" onClick={()=>void sample()}>Load illustrative actions</button><a href={`${base}/api/v1/samples/planner-example.json`} download>Download planner JSON</a><a href={`${base}/api/v1/samples/FIELD_PROTOCOL.md`} download>Field evidence checklist</a></div>
 <label>Import candidate actions (.json)<input type="file" accept=".json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>100000)throw Error('File must be smaller than 100 KB');applySample(JSON.parse((await f.text()).replace(/^\uFEFF/,'')));setError('');}catch(err){setError(String(err));}}}/></label>
 {example&&<p className="source-banner">Illustrative assumptions loaded. Replace costs and effects with site-reviewed values before using a live scenario. No assignment is created by this comparison.</p>}
 <div className="field-grid"><label>Available budget (same currency as costs)<input aria-label="Planning budget" type="number" min={0} value={budget} onChange={e=>{setBudget(+e.target.value);setResult(null);}}/></label><label>Action name<input value={entry.name} placeholder="Facility-approved action" onChange={e=>setEntry({...entry,name:e.target.value})}/></label>
 {([['cost','Total action cost'],['pm25_reduction_pct','Assumed ambient PM2.5 reduction (%)'],['pm10_reduction_pct','Assumed ambient PM10 reduction (%)'],['start_hour','First active forecast hour (1–24)'],['end_hour','Last active forecast hour (1–24)']] as const).map(([key,label])=><label key={key}>{label}<input type="number" min={key.includes('hour')?1:0} max={key.includes('hour')?24:key.includes('pct')?80:100000000} value={entry[key]} onChange={e=>setEntry({...entry,[key]:+e.target.value})}/></label>)}</div>
 <button className="button" disabled={!valid||options.length>=12} onClick={()=>{setOptions([...options,entry]);setEntry({...entry,name:''});setResult(null);}}>Add candidate action</button>
 <div className="table-scroll"><table><thead><tr><th>Candidate</th><th>Cost</th><th>PM2.5 / PM10 effects</th><th>Hours</th><th></th></tr></thead><tbody>{options.map((o,i)=><tr key={i}><td>{o.name}</td><td>{o.cost.toLocaleString()}</td><td>{o.pm25_reduction_pct}% / {o.pm10_reduction_pct}%</td><td>{o.start_hour}–{o.end_hour}</td><td><button onClick={()=>{setOptions(options.filter((_,j)=>j!==i));setResult(null);}}>Remove</button></td></tr>)}</tbody></table></div>
 <button className="button primary" disabled={busy||!options.length} onClick={()=>void run()}>{busy?'Comparing combinations…':'Compare feasible combinations'}</button>{error&&<p role="alert">{error}</p>}
 {result&&<div className="workflow-result"><h3>{mode==='demo'?'Synthetic presentation result':'Scenario result — approval still required'}</h3><p>Selected: {result.selected.map(o=>o.name).join(', ')||'No action improves the objective within this budget'}. Cost: {result.cost.toLocaleString()} of {budget.toLocaleString()}.</p><p>Forecast window: {new Date(result.forecast_start).toLocaleString()} – {new Date(result.forecast_end).toLocaleString()}.</p><p>High-risk forecast hours: <strong>{result.baseline_peak_hours} → {result.scenario_peak_hours}</strong>. Assumed reduction: {result.scenario_reduction_pct==null?'Undefined because the baseline has no high-risk hours':`${result.scenario_reduction_pct}%`}.</p><p>{result.note}</p><p>Next: check feasibility with the site operator, assign an approved action, then collect independent measurements. Optimizing the assumptions does not validate them.</p></div>}
 </article>;
}
